options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - -t
    - 'us-central1-docker.pkg.dev/${PROJECT_ID}/ppdb-docker-repo/stage-chunk-image:latest'
    - .
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/ppdb-docker-repo/stage-chunk-image:latest'
