name: Int - Stage Chunk Cloud Run Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: int/stage-chunk

    env:
      PROJECT_ID: ${{ vars.GCP_INT_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      SERVICE_NAME: trigger-stage-chunk
      APP_SOURCE_PATH: stage_chunk
      RUNTIME: 'python313'
      ENTRY_POINT: 'trigger_stage_chunk'
      CPU: ${{ vars.TRIGGER_STAGE_CHUNK_CPU }}
      MEMORY: ${{ vars.TRIGGER_STAGE_CHUNK_MEMORY }}
      TIMEOUT: ${{ vars.TRIGGER_STAGE_CHUNK_TIMEOUT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_INT }}

      - name: 'Deploy to Cloud Run Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v4'
        with:
          name: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source_dir: ${{ env.APP_SOURCE_PATH }}
          runtime: ${{ env.RUNTIME }}
          entry_point: ${{ env.ENTRY_POINT }}
          cpu: ${{ env.CPU }}
          memory: ${{ env.MEMORY }}
          service_timeout: ${{ env.TIMEOUT }}
