name: Dev - Track Chunk Cloud Run Deploy

on:
  pull_request:
    paths:
      - 'track_chunk/*.py'
      - 'track_chunk/requirements.txt'
  push:
    branches:
      - main
    paths:
      - 'track_chunk/*.py'
      - 'track_chunk/requirements.txt'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev/track-chunk

    env:
      PROJECT_ID: ${{ vars.GCP_DEV_PROJECT_ID }}
      REGION: ${{ vars.GCP_REGION }}
      SERVICE_NAME: track-chunk
      APP_SOURCE_PATH: track_chunk
      RUNTIME: 'python313'
      ENTRY_POINT: 'track_chunk'
      CPU: ${{ vars.TRACK_CHUNK_CPU }}
      MEMORY: ${{ vars.TRACK_CHUNK_MEMORY }}
      TIMEOUT: ${{ vars.TRACK_CHUNK_TIMEOUT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_DEV }}

      - name: 'Deploy to Cloud Run Functions'
        uses: 'google-github-actions/deploy-cloud-functions@v4'
        with:
          name: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          source_dir: ${{ env.APP_SOURCE_PATH }}
          runtime: ${{ env.RUNTIME }}
          entry_point: ${{ env.ENTRY_POINT }}
          cpu: ${{ env.CPU }}
          memory: ${{ env.MEMORY }}
          service_timeout: ${{ env.TIMEOUT }}
